#!/bin/sh
#
#
PROJ_URL=https://api.github.com/repos/dtaveras/drnews-webapp/issues
echo "Checking for correct Issue Reference Number"

COMMIT_REF_NUM=$(sed -ne 's/.*\#\([0-9]*\).*/\1/p' $1)

if [ -z "$COMMIT_REF_NUM" ];then
    echo "Commit Failed: Could not parse Reference Number"
    exit 1
fi

echo Parsed Commit Ref Num: $COMMIT_REF_NUM

echo "Fetching tickets"
TICKET=`curl -s $PROJ_URL | jq "[.[] | {id: .id, title: .title, issueNumber: .number, state: .state, type: .labels[0].name, createdTime: .created_at, updatedTime: .updated_at, ClosedAt: .closed_at}] | .[] | select(.issueNumber == $COMMIT_REF_NUM)"`

if [ ! -z "$TICKET" ]; then
    STATE=`echo "$TICKET" | jq '.state'`
    if [ "$STATE" == '"open"' ]; then
	echo "Found open ticket proceeding to commiting ..."
	echo $TICKET | jq '.'
    else
	echo "Commit Failed: ticket #$COMMIT_REF_NUM is $STATE"
	exit 1
    fi
else
    echo "Commit Failed: Ticket #$COMMIT_REF_NUM does not exist"
    exit 1
fi

exit 1
